<a href="https://colab.research.google.com/github/Lucas-Souza21/TP547-LucasSSouza/blob/main/Lista3Markov/Lista3CadeiasDeMarkovEx2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip install matplotlib
!pip install scipy
!pip install numpy.linalg

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 17.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [5]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import matrix_power

n=100000 #numero de simulacoes
x0=[0, 0.5, 0.5, 0]# vetor de probabilidade inicial
probabilidades_transicao = np.array([
    [1, 0, 0, 0],
    [0.3, 0.4, 0.3, 0],
    [0, 0.3, 0.4, 0.3],
    [0, 0, 0, 1]
    ])  # matriz de transicao de um passo
chain2 = np.zeros(n,int) #vetor para armazenar os estados no passo escolhido, passo 0 estado inicial, passo 1 uma transicao, ...
chain3 = np.zeros(n,int) #vetor para armazenar os estados no passo escolhido, passo 0 estado inicial, passo 1 uma transicao, ...
passo = 5 #Quandos passos para a resposta
passomed = 0

for j in np.arange(0,n,1):

    r1 = np.random.uniform(0,1) #geracao de varivel uniforme para escolha do valor inicial
    acumulada = np.cumsum(x0) #gera um vetor [x1,x1+x2,...,1]
    valor_inicial = np.argmax(acumulada>r1) #aplica o método de geracao baseado na CDF
    chain_length = 25 #numero de transicoes na cadeia, tem que ser maior que o passo escolhido.
    chain = np.zeros(chain_length,int) #vetor que vai armazenar todas as transicoes feitas na cadeia
    chain[0]=valor_inicial
    varaux = 0

    for i in np.arange(1,chain_length,1):
        Linha_atual = probabilidades_transicao[chain[i-1]]#pega a linha referente ao estado atual
        acumulada = np.cumsum(Linha_atual)
        r = np.random.uniform(0,1)
        chain[i] = np.argmax(acumulada>r)#aplica o método de geracao baseado na CDF
        if (chain[i] == 0 or chain[i] == 3) and varaux == 0:
          passomed = passomed + i
          varaux = 1


    chain3[j] =chain[3]
    chain2[j] =chain[passo]#armazena o estado no passo em chain2

#calculo de estatisticas por monte carlo
prob1=np.sum(chain2==5)/n
prob2=((np.sum(chain3==0))+np.sum(chain3==3))/n
passomed = passomed/n

print("A matriz de transição de 1 passo é de:")
print(probabilidades_transicao)
print(f"A probabilidade da mosca morrer após 3 horas é em média {prob2}.")
print(f"A quantidade media de horas até a mosca encontrar uma das aranhas é de: {passomed}.")


A matriz de transição de 1 passo é de:
[[1.  0.  0.  0. ]
 [0.3 0.4 0.3 0. ]
 [0.  0.3 0.4 0.3]
 [0.  0.  0.  1. ]]
A probabilidade da mosca morrer após 3 horas é em média 0.65707.
A quantidade media de horas até a mosca encontrar uma das aranhas é de: 3.333.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import matrix_power

Q = np.array([
    [0.4 , 0.3],
     [0.3 , 0.4]
    ])
I = np.array([
    [1, 0],
     [0, 1]
     ])
R = np.array([
    [0.3 , 0],
     [0 , 0.3]
    ])

Naux = I - Q
N = np.linalg.inv(Naux)
c = np.array([[1], [1]])
t = N @ c;
B = N @ R;

print(t)

print(B)

[[3.33333333]
 [3.33333333]]
[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]
